/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-05-10 15:08:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.assemble;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Frame bottom</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/js/jquery.js\"></script>\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/css/common_style_blue.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody{\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\timg{\r\n");
      out.write("\t\t\tvertical-align: inherit;\r\n");
      out.write("\t\t\tborder:0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ta:link, a:hover, a:visited {\r\n");
      out.write("\t\t\tcolor: #A9DCFF;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#StatusBar {\r\n");
      out.write("\t\t\tbackground-color: #4386B7;\r\n");
      out.write("\t\t\tborder-top: 1px solid #FFFFFF;\r\n");
      out.write("\t\t\theight: 19px;\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#StatusBar #StatusBar_Links {\r\n");
      out.write("\t\t\tcolor: #A9DCFF;\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t\tfont-family: \"宋体\";\r\n");
      out.write("\t\t\tfont-size: 12px;\r\n");
      out.write("\t\t\tpadding-left: 20px;\r\n");
      out.write("\t\t\tpadding-top: 3px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#StatusBar #StatusBar_Right {\r\n");
      out.write("\t\t\tcolor: #A9DCFF;\r\n");
      out.write("\t\t\tfloat: right;\r\n");
      out.write("\t\t\tfont-family: \"宋体\";\r\n");
      out.write("\t\t\tfont-size: 12px;\r\n");
      out.write("\t\t\tpadding-right: 20px;\r\n");
      out.write("\t\t\tpadding-top: 4px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body> \r\n");
      out.write("\r\n");
      out.write("<div id=\"StatusBar\">\r\n");
      out.write("\t<!-- 链接 -->\r\n");
      out.write("    <div id=\"StatusBar_Links\">\r\n");
      out.write("\t\t<a href=\"http://www.nyist.edu.cn/\" target=\"_blank\">南阳理工学院</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- 右侧功能按钮 -->\r\n");
      out.write("    <div id=\"StatusBar_Right\">\r\n");
      out.write("\t\t<!-- 版本 -->\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t<img border=\"0\" width=\"11\" height=\"11\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/info.gif\" /> \r\n");
      out.write("\t\t\t<img border=\"0\" width=\"40\" height=\"11\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/version.gif\" />\r\n");
      out.write("\t\t</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
