/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-05-10 15:08:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.assemble;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Frame top</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/js/jquery.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/js/page_common.js\"></script>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/css/common_style_blue.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("margin: 0;\r\n");
      out.write("}\r\n");
      out.write("#Head_1 {\r\n");
      out.write("    background: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/img/top_head1_bg.gif\") repeat-x scroll 0 0 transparent;\r\n");
      out.write("    height: 64px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("#Head_1 #Head_1_Logo {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("    left: 20px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 12px;\r\n");
      out.write("\tcolor: #F1F9FE;\r\n");
      out.write("    font-family: Arial Black,Arial;\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("}\r\n");
      out.write("#Head_1 #Head_1_UserWelcome {\r\n");
      out.write("    float: right;\r\n");
      out.write("    color: #B3E1FF;\r\n");
      out.write("    font-family: \"宋体\";\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("\tpadding-top: 11px;\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("#Head_1 #Head_1_FunctionButton {\r\n");
      out.write("    float: left;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 5px;\r\n");
      out.write("    top: 35px;\r\n");
      out.write("\tmargin-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("#Head_1 #Head_1_FunctionButton img {\r\n");
      out.write("margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 {\r\n");
      out.write("   background: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/img/top_head2_bg.gif\") repeat-x scroll 0 0 transparent;\r\n");
      out.write("    border-bottom: 1px solid #FFFFFF;\r\n");
      out.write("    border-top: 1px solid #A0C6E1;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 #Head2_Awoke {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    padding-left: 19px;\r\n");
      out.write("    padding-top: 2px;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 #Head2_Awoke #AwokeNum {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 20px;\r\n");
      out.write("\ttop: 68px;\t\r\n");
      out.write("\twidth: 406px;\r\n");
      out.write("\t/*height: 21px;*/\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tpadding-top: 2px;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 #Head2_Awoke #AwokeNum li {\r\n");
      out.write("  float: left;\r\n");
      out.write("    margin: 3px;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 #Head2_Awoke #AwokeNum a {\r\n");
      out.write("   color: #FFFFFF;\r\n");
      out.write("    font-family: \"宋体\";\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 #Head2_Awoke #AwokeNum .Line {\r\n");
      out.write("    border-left: 1px solid #005A98;\r\n");
      out.write("    border-right: 1px solid #A0C6E1;\r\n");
      out.write("    height: 17px;\r\n");
      out.write("    width: 0px;\r\n");
      out.write("}\r\n");
      out.write("#Head_2 #Head2_FunctionList, .Head2_FunctionList {\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("    float: right;\r\n");
      out.write("    font-family: \"宋体\";\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    padding-right: 26px;\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" \t\r\n");
      out.write("\t<!-- 上部 -->\r\n");
      out.write("\t<div id=\"Head_1\">\r\n");
      out.write("\t\t<!-- 标题 -->\r\n");
      out.write("\t\t<div id=\"Head_1_Logo\">\r\n");
      out.write("\t\t\t<b style=\"font-family: '黑体'\">学生任务信息管理平台</b> <!-- <img border=\"0\" src=\"style/images/logo.png\" /> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<!-- 欢迎用户的文字 -->\r\n");
      out.write("\t\t<div id=\"Head_1_UserWelcome\">\r\n");
      out.write("\t\t\t<img border=\"0\" width=\"13\" height=\"14\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/user.gif\" /> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t您好，<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.Student.sname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</b>同学\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 一些链接按钮 -->\r\n");
      out.write("\t\t<div id=\"Head_1_FunctionButton\">\r\n");
      out.write("\t\t\t<a target=\"right\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t<img width=\"78\" height=\"20\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/help2.gif\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logout.action\">\r\n");
      out.write("\t\t\t\t<img width=\"78\" height=\"20\" alt=\"退出系统\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/logout.gif\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 下部 -->\r\n");
      out.write("    <div id=\"Head_2\">\r\n");
      out.write("\t\t<!-- 任务提醒 -->\r\n");
      out.write("        <div id=\"Head2_Awoke\">\r\n");
      out.write("\t\t\t<ul id=\"AwokeNum\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("            </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"Head2_FunctionList\" style=\"float:left\">\r\n");
      out.write("\t\t\t<a href=\"javascript: window.parent.right.history.back();\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/Header_back.gif\" width=\"24\" height=\"24\" style=\"margin-top: -8px;\"/>\r\n");
      out.write("\t\t\t\t<b>后退</b>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"javascript: window.parent.right.history.forward();\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/Header_forward.gif\" width=\"24\" height=\"24\" style=\"margin-top: -8px;\"/>\r\n");
      out.write("\t\t\t\t<b>前进</b>\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div id=\"Head2_FunctionList\">\r\n");
      out.write("\t\t\t<!-- \r\n");
      out.write("\t\t\t\t如果使用 window.parent.right.location.reload(true); 则IE与FF都可以使用，Chrome不可以。\r\n");
      out.write("\t\t\t\t在Chrome中 alert(window.parent.right.document); 显示的值是 undefined！为什么？\r\n");
      out.write("\t\t\t\t使用 window.parent.right.history.go(0) 实现刷新，在IE、Chrome中都可以运行，但在FF中不可以！（但没有测试什么时候会使用缓存）。\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\t\t\t<a href=\"javascript: window.parent.right.history.go(0);\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/Header_refresh.gif\" width=\"24\" height=\"24\" style=\"margin-top: -8px;\"/>\r\n");
      out.write("\t\t\t\t<b>刷新(IE、Chrome)</b>\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"javascript: window.parent.right.location.reload(true);\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/images/Header_refresh.gif\" width=\"24\" height=\"24\" style=\"margin-top: -8px;\"/>\r\n");
      out.write("\t\t\t\t<b>刷新(Firefox)</b>\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
