/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-05-10 15:06:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>登录界面</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/StudentCMSpage/detail/style/js/jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"iconfont/style.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{color:#fff; font-family:\"微软雅黑\"; font-size:14px;}\r\n");
      out.write("\t.wrap1{position:absolute; top:0; right:0; bottom:0; left:0; margin:auto }/*把整个屏幕真正撑开--而且能自己实现居中*/\r\n");
      out.write("\t.main_content{background:url(images/main_bg.png) repeat; margin-left:auto; margin-right:auto; text-align:left; float:none; border-radius:8px;}\r\n");
      out.write("\t.form-group{position:relative;}\r\n");
      out.write("\t.login_btn{display:block; background:#3872f6; color:#fff; font-size:15px; width:100%; line-height:50px; border-radius:3px; border:none; }\r\n");
      out.write("\t.login_input{width:100%; border:1px solid #3872f6; border-radius:3px; line-height:40px; padding:2px 5px 2px 30px; background:none;}\r\n");
      out.write("\t.icon_font{position:absolute; bottom:15px; left:10px; font-size:18px; color:#3872f6;}\r\n");
      out.write("\t.font16{font-size:16px;}\r\n");
      out.write("\t.mg-t20{margin-top:20px;}\r\n");
      out.write("\t@media (min-width:200px){.pd-xs-20{padding:20px;}}\r\n");
      out.write("\t@media (min-width:768px){.pd-sm-50{padding:50px;}}\r\n");
      out.write("\t#grad {\r\n");
      out.write("\t  background: -webkit-linear-gradient(#4990c1, #52a3d2, #6186a3); /* Safari 5.1 - 6.0 */\r\n");
      out.write("\t  background: -o-linear-gradient(#4990c1, #52a3d2, #6186a3); /* Opera 11.1 - 12.0 */\r\n");
      out.write("\t  background: -moz-linear-gradient(#4990c1, #52a3d2, #6186a3); /* Firefox 3.6 - 15 */\r\n");
      out.write("\t  background: linear-gradient(#4990c1, #52a3d2, #6186a3); /* 标准的语法 */\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:url(images/a2.jpg) no-repeat;width: 100%;height: 100%;\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container wrap1\" style=\"height:450px;\">\r\n");
      out.write("            <h2 class=\"mg-b20 text-center\">南阳理工学院软件学院</h2>\r\n");
      out.write("            <div class=\"col-sm-8 col-md-5 center-auto pd-sm-50 pd-xs-20 main_content\">\r\n");
      out.write("            \t<p id=\"ts\" style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ts }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("                <p class=\"text-center font16\">用户登录</p>\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/finduser.action\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group mg-t20\">\r\n");
      out.write("                        <i class=\"icon-user icon_font\"></i>\r\n");
      out.write("                        <input type=\"text\" class=\"login_input\" id=\"username\" name=\"sno\" placeholder=\"请输入用户名\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mg-t20\">\r\n");
      out.write("                        <i class=\"icon-lock icon_font\"></i>\r\n");
      out.write("                        <input type=\"password\" class=\"login_input\" id=\"password\" name=\"password\" placeholder=\"请输入密码\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <button style=\"submit\" class=\"login_btn\" onclick=\"return login()\">登 录</button>\r\n");
      out.write("               </form>\r\n");
      out.write("        </div><!--row end-->\r\n");
      out.write("    </div><!--container end-->\r\n");
      out.write("           \r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function login(){\r\n");
      out.write("\tif($(\"#username\").val()==\"\" ||$.trim($(\"#username\").val()).length<0){\r\n");
      out.write("\t\t$(\"#ts\").html(\"用户名不能为空！\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#password\").val()==\"\" ||$.trim($(\"#password\").val()).length<0){\r\n");
      out.write("\t\t$(\"#ts\").html(\"密码不能为空！\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\ttrue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
